source 'https://rubygems.org'

ruby '3.0.2'

gem 'sinatra', '2.1.0'
gem 'rerun', '0.13.0'
gem 'mhartl_palindrome', '~> 0.2.1'

group :test do
  gem 'rack-test', '1.0.0' # for testing sinatra
  gem 'rake', '12.3.1' # for running tests
  gem 'minitest', '5.11.3' # for testing
  gem 'minitest-reporters', '1.2.0' # for better test output
  gem 'nokogiri', '1.15.6' # for parsing HTML in tests
end
